"""Auto-generated migration for V10 domain

Revision ID: 086d66c061ab
Revises: 45f01f3e14a0
Create Date: 2026-01-26 17:18:16.938160

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '086d66c061ab'
down_revision: Union[str, None] = '45f01f3e14a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # langchain_pg_* 테이블은 LangChain PGVector에서 관리하므로 제외됨
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # langchain_pg_* 테이블은 LangChain PGVector에서 관리하므로 제외됨
    pass
    # ### end Alembic commands ###
