"""Auto-generated migration for V10 domain

Revision ID: 0aefb175cf2f
Revises: 18d69c346c09
Create Date: 2026-02-01 18:23:16.724073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aefb175cf2f'
down_revision: Union[str, None] = '18d69c346c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
