"""Auto-generated migration for V10 domain

Revision ID: 0ed2ac7e8dd4
Revises: f51a876b4a2d
Create Date: 2026-01-27 11:58:12.691904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed2ac7e8dd4'
down_revision: Union[str, None] = 'f51a876b4a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
