"""Auto-generated migration for V10 domain

Revision ID: 0edb95936e10
Revises: 0ed2ac7e8dd4
Create Date: 2026-01-27 12:36:12.045137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edb95936e10'
down_revision: Union[str, None] = '0ed2ac7e8dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
