"""Auto-generated migration for V10 domain

Revision ID: 18d69c346c09
Revises: cad2b465f202
Create Date: 2026-02-01 17:27:41.631195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d69c346c09'
down_revision: Union[str, None] = 'cad2b465f202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'stadium_id',
               existing_type=sa.BIGINT(),
               comment='경기장 ID',
               existing_comment='경기장 ID (FK -> stadiums.id)',
               existing_nullable=False)
    op.alter_column('schedules', 'hometeam_id',
               existing_type=sa.BIGINT(),
               comment='홈팀 ID',
               existing_comment='홈팀 ID (FK -> teams.id)',
               existing_nullable=False)
    op.alter_column('schedules', 'awayteam_id',
               existing_type=sa.BIGINT(),
               comment='원정팀 ID',
               existing_comment='원정팀 ID (FK -> teams.id)',
               existing_nullable=False)
    op.alter_column('stadiums', 'hometeam_id',
               existing_type=sa.BIGINT(),
               comment='홈팀 ID',
               existing_comment='홈팀 ID (FK -> teams.id)',
               existing_nullable=True)
    op.drop_constraint(op.f('stadiums_hometeam_id_fkey'), 'stadiums', type_='foreignkey')
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.BIGINT(),
               comment='경기장 ID',
               existing_comment='경기장 ID (FK -> stadiums.id)',
               existing_nullable=True)
    op.drop_constraint(op.f('teams_stadium_id_fkey'), 'teams', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('teams_stadium_id_fkey'), 'teams', 'stadiums', ['stadium_id'], ['id'])
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.BIGINT(),
               comment='경기장 ID (FK -> stadiums.id)',
               existing_comment='경기장 ID',
               existing_nullable=True)
    op.create_foreign_key(op.f('stadiums_hometeam_id_fkey'), 'stadiums', 'teams', ['hometeam_id'], ['id'])
    op.alter_column('stadiums', 'hometeam_id',
               existing_type=sa.BIGINT(),
               comment='홈팀 ID (FK -> teams.id)',
               existing_comment='홈팀 ID',
               existing_nullable=True)
    op.alter_column('schedules', 'awayteam_id',
               existing_type=sa.BIGINT(),
               comment='원정팀 ID (FK -> teams.id)',
               existing_comment='원정팀 ID',
               existing_nullable=False)
    op.alter_column('schedules', 'hometeam_id',
               existing_type=sa.BIGINT(),
               comment='홈팀 ID (FK -> teams.id)',
               existing_comment='홈팀 ID',
               existing_nullable=False)
    op.alter_column('schedules', 'stadium_id',
               existing_type=sa.BIGINT(),
               comment='경기장 ID (FK -> stadiums.id)',
               existing_comment='경기장 ID',
               existing_nullable=False)
    # ### end Alembic commands ###
