"""Auto-generated migration

Revision ID: 3be65c3c1c38
Revises: ca09c0eccaf3
Create Date: 2026-02-05 18:13:04.675213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be65c3c1c38'
down_revision: Union[str, None] = 'ca09c0eccaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
