"""Auto-generated migration for V10 domain

Revision ID: 50c1476480a4
Revises: a0351ce157ab
Create Date: 2026-01-27 17:16:02.621138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c1476480a4'
down_revision: Union[str, None] = 'a0351ce157ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
