"""Auto-generated migration

Revision ID: 5d1b1bb2a86b
Revises: 9e89ac474783
Create Date: 2026-02-03 10:54:16.823717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1b1bb2a86b'
down_revision: Union[str, None] = '9e89ac474783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
