"""Auto-generated migration for V10 domain

Revision ID: 5df98c0e25e0
Revises: squashed_v10
Create Date: 2026-01-30 13:38:18.541050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df98c0e25e0'
down_revision: Union[str, None] = 'squashed_v10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
