"""Auto-generated migration for V10 domain

Revision ID: 670ae954d198
Revises: 7e99f4f1813b
Create Date: 2026-01-30 18:16:43.821283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670ae954d198'
down_revision: Union[str, None] = '7e99f4f1813b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
