"""Auto-generated migration for V10 domain

Revision ID: 77719fd6cd0a
Revises: face890c513b
Create Date: 2026-02-01 20:48:50.682916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77719fd6cd0a'
down_revision: Union[str, None] = 'face890c513b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
