"""Auto-generated migration

Revision ID: 7a95d4de9ef9
Revises: 6ddd5608d90f
Create Date: 2026-02-02 21:17:33.617505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a95d4de9ef9'
down_revision: Union[str, None] = '6ddd5608d90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
