"""Auto-generated migration for V10 domain

Revision ID: 7e99f4f1813b
Revises: 969c71f04ed7
Create Date: 2026-01-30 18:06:55.550311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e99f4f1813b'
down_revision: Union[str, None] = '969c71f04ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
