"""Auto-generated migration for V10 domain

Revision ID: 8f751a18b1b7
Revises: f50e14f4283d
Create Date: 2026-01-30 17:17:51.900946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f751a18b1b7'
down_revision: Union[str, None] = 'f50e14f4283d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
