"""Auto-generated migration for V10 domain

Revision ID: 969c71f04ed7
Revises: dfa38315e183
Create Date: 2026-01-30 17:54:27.113212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969c71f04ed7'
down_revision: Union[str, None] = 'dfa38315e183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
