"""Auto-generated migration for V10 domain

Revision ID: a34785dcf7b6
Revises: 0edb95936e10
Create Date: 2026-01-27 15:03:41.380738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34785dcf7b6'
down_revision: Union[str, None] = '0edb95936e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
