"""Auto-generated migration for V10 domain

Revision ID: bd7faa7b2e04
Revises: 0aefb175cf2f
Create Date: 2026-02-01 18:31:22.646473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7faa7b2e04'
down_revision: Union[str, None] = '0aefb175cf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
