"""Auto-generated migration

Revision ID: ca09c0eccaf3
Revises: e82be28bc0b7
Create Date: 2026-02-05 17:34:05.343822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca09c0eccaf3'
down_revision: Union[str, None] = 'e82be28bc0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
