"""Auto-generated migration for V10 domain

Revision ID: f50e14f4283d
Revises: add_exaone_emb
Create Date: 2026-01-30 17:11:27.162104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e14f4283d'
down_revision: Union[str, None] = 'add_exaone_emb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
