"""Auto-generated migration for V10 domain

Revision ID: f51a876b4a2d
Revises: c79aed452485
Create Date: 2026-01-27 11:42:15.206975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51a876b4a2d'
down_revision: Union[str, None] = 'c79aed452485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
