"""Initial migration for V10 domain (auto-generated)

Revision ID: f9b12e7f11ec
Revises:
Create Date: 2026-01-26 15:23:30.040894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f9b12e7f11ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 순환 참조 해결: FK 없이 먼저 테이블 생성 후 FK 추가

    # 1. teams 테이블 생성 (FK 없이)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='팀 ID'),
    sa.Column('stadium_id', sa.BigInteger(), nullable=True, comment='경기장 ID (FK -> stadiums.id)'),
    sa.Column('team_code', sa.String(length=10), nullable=False, comment='팀 코드'),
    sa.Column('region_name', sa.String(length=50), nullable=True, comment='지역명'),
    sa.Column('team_name', sa.String(length=100), nullable=False, comment='팀 이름'),
    sa.Column('e_team_name', sa.String(length=100), nullable=True, comment='팀 영문 이름'),
    sa.Column('orig_yyyy', sa.String(length=4), nullable=True, comment='창단 연도'),
    sa.Column('zip_code1', sa.String(length=10), nullable=True, comment='우편번호 앞자리'),
    sa.Column('zip_code2', sa.String(length=10), nullable=True, comment='우편번호 뒷자리'),
    sa.Column('address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('ddd', sa.String(length=10), nullable=True, comment='지역번호'),
    sa.Column('tel', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('fax', sa.String(length=20), nullable=True, comment='팩스번호'),
    sa.Column('homepage', sa.Text(), nullable=True, comment='홈페이지'),
    sa.Column('owner', sa.String(length=100), nullable=True, comment='구단주'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )

    # 2. stadiums 테이블 생성 (FK 없이)
    op.create_table('stadiums',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='경기장 ID'),
    sa.Column('stadium_code', sa.String(length=10), nullable=False, comment='경기장 코드'),
    sa.Column('statdium_name', sa.String(length=100), nullable=False, comment='경기장 이름'),
    sa.Column('hometeam_id', sa.BigInteger(), nullable=True, comment='홈팀 ID (FK -> teams.id)'),
    sa.Column('hometeam_code', sa.String(length=10), nullable=True, comment='홈팀 코드'),
    sa.Column('seat_count', sa.Integer(), nullable=True, comment='좌석 수'),
    sa.Column('address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('ddd', sa.String(length=10), nullable=True, comment='지역번호'),
    sa.Column('tel', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stadium_code')
    )

    # 3. 순환 참조 FK 추가: stadiums.hometeam_id -> teams.id
    op.create_foreign_key(
        'stadiums_hometeam_id_fkey',
        'stadiums', 'teams',
        ['hometeam_id'], ['id']
    )

    # 4. 순환 참조 FK 추가: teams.stadium_id -> stadiums.id
    op.create_foreign_key(
        'teams_stadium_id_fkey',
        'teams', 'stadiums',
        ['stadium_id'], ['id']
    )

    # 5. players 테이블 생성 (teams에 의존)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='선수 ID'),
    sa.Column('team_id', sa.BigInteger(), nullable=False, comment='팀 ID (FK -> teams.id)'),
    sa.Column('player_name', sa.String(length=100), nullable=False, comment='선수 이름'),
    sa.Column('e_player_name', sa.String(length=100), nullable=True, comment='선수 영문 이름'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='별명'),
    sa.Column('join_yyyy', sa.String(length=4), nullable=True, comment='입단 연도'),
    sa.Column('position', sa.String(length=10), nullable=True, comment='포지션 (GK, DF, MF, FW)'),
    sa.Column('back_no', sa.Integer(), nullable=True, comment='등번호'),
    sa.Column('nation', sa.String(length=50), nullable=True, comment='국적'),
    sa.Column('birth_date', sa.String(length=10), nullable=True, comment='생년월일 (YYYY-MM-DD)'),
    sa.Column('solar', sa.String(length=1), nullable=True, comment='양력/음력 구분 (1: 양력, 2: 음력)'),
    sa.Column('height', sa.Integer(), nullable=True, comment='키 (cm)'),
    sa.Column('weight', sa.Integer(), nullable=True, comment='몸무게 (kg)'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 6. schedules 테이블 생성 (teams, stadiums에 의존)
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='경기 ID'),
    sa.Column('stadium_id', sa.BigInteger(), nullable=False, comment='경기장 ID (FK -> stadiums.id)'),
    sa.Column('hometeam_id', sa.BigInteger(), nullable=False, comment='홈팀 ID (FK -> teams.id)'),
    sa.Column('awayteam_id', sa.BigInteger(), nullable=False, comment='원정팀 ID (FK -> teams.id)'),
    sa.Column('stadium_code', sa.String(length=10), nullable=False, comment='경기장 코드'),
    sa.Column('sche_date', sa.String(length=8), nullable=False, comment='경기 일자 (YYYYMMDD)'),
    sa.Column('gubun', sa.String(length=1), nullable=False, comment='경기 구분 (Y/N)'),
    sa.Column('hometeam_code', sa.String(length=10), nullable=False, comment='홈팀 코드'),
    sa.Column('awayteam_code', sa.String(length=10), nullable=False, comment='원정팀 코드'),
    sa.Column('home_score', sa.Integer(), nullable=True, comment='홈팀 점수'),
    sa.Column('away_score', sa.Integer(), nullable=True, comment='원정팀 점수'),
    sa.ForeignKeyConstraint(['awayteam_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['hometeam_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 역순으로 테이블 삭제 및 FK 제거

    # 1. 의존 테이블 먼저 삭제
    op.drop_table('schedules')
    op.drop_table('players')

    # 2. 순환 참조 FK 제거
    op.drop_constraint('teams_stadium_id_fkey', 'teams', type_='foreignkey')
    op.drop_constraint('stadiums_hometeam_id_fkey', 'stadiums', type_='foreignkey')

    # 3. 기본 테이블 삭제
    op.drop_table('stadiums')
    op.drop_table('teams')
    # ### end Alembic commands ###
